[package]
name = "rusty_cryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_derive = "*"
serde_json = "*"
serde = "*"
tokio-core = "*"
hyper = "*"
hyper-tls = "*"
futures = "*"
oauth-client = "*"
twitter-api = "*"